---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: c1890e1a05db592924e12056000a39fe495a2822
    app.quarkus.io/build-timestamp: 2023-01-14 - 11:21:16 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: qk8s
  name: qk8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: qk8s
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: c1890e1a05db592924e12056000a39fe495a2822
        app.quarkus.io/build-timestamp: 2023-01-14 - 11:21:16 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: qk8s
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: qk9s-aws-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: qk9s-aws-secret
                  key: AWS_SECRET_ACCESS_KEY
          image: 262280523204.dkr.ecr.me-central-1.amazonaws.com/qk8s:latest
          imagePullPolicy: Always
          name: qk8s
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
      serviceAccountName: qk8s
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: c1890e1a05db592924e12056000a39fe495a2822
    app.quarkus.io/build-timestamp: 2023-01-14 - 11:21:16 +0000
  labels:
    app.kubernetes.io/name: qk8s
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: qk8s
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: qk8s
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: c1890e1a05db592924e12056000a39fe495a2822
    app.quarkus.io/build-timestamp: 2023-01-14 - 11:21:16 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: qk8s
  name: qk8s
imagePullSecrets:
  - name: qk9s-ecr-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qk8s-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: qk8s
