apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  env:
    - name: WAL_S3_BUCKET
      value: wal-s3-backup-bucket
    - name: AWS_REGION
      value: ap-south-1
  teamId: "acid"
  volume:
    size: 2Gi
  numberOfInstances: 1
  users:
    zalando:  # database owner
      - superuser
      - createdb
    foo_user: []  # role for application foo
  databases:
    quarkus: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
