apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  enableMasterLoadBalancer: true
  teamId: "acid"
  volume:
    size: 2Gi
  numberOfInstances: 2
  users:
    zalando:  # database owner
      - superuser
      - createdb
    foo_user: []  # role for application foo
  databases:
    foo: zalando  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "14"
